# Generated by Django 4.1.4 on 2022-12-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pupa', '0002_pupavolunteer_teammember_gallery_caption_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=1500)),
                ('contact_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
